import React from 'react'
import Head from "next/head";
import Header from "../../components/Header";

function About() {
  return (
    <>
      <Head>
        <title>À Propos | Menuiserie Artisanale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="about">
        <Header />
        À Propos Page
      </section>
    </>
  )
}

export default About