import Head from "next/head";
import React, {useRef } from "react";
import Transition from "../../utils/Transition";

const Catalogue = () => {
  const catalogueContainerRef = useRef(null);

  return (
    <>
      <Head>
        <title>Catalogue | Menuiserie Artisanale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="catalogue" ref={catalogueContainerRef}>
        <h1>Catalogue</h1>
      </section>
    </>
  );
};

export default Transition(Catalogue);
