import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import Header from "../../components/Header";
import catalogueImg from "../../public/images/section/catalogue.jpg";
import catalogueImgmobile from "../../public/images/section/catalogueMobile.jpg";
import { ArrowIcon } from "../../utils/icons";

const Catalogue = () => {
  return (
    <>
      <Head>
        <title>Catalogue | Menuiserie Artisanale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="catalogue">
        <Header />
        <div className="catalogue_container">
          <div className="catalogue_layout_left">
            <Image src={catalogueImg} alt="catalogue" />
          </div>

          <div className="catalogue_layout">
            <div className="catalogue_head">
              <div className="hidden">
                <h5 className="subtitle">
                  Notre
                </h5>
              </div>
              <div className="hidden">
                <h1 className="catalogue_introduction title">
                Catalogue
                </h1>
              </div>
              <p className="catalogue_introduction introduction">
                Décor Ta Kaz propose une variété de produits et de services pour
                répondre aux besoins de ses clients. Dans notre catalogue, vous
                trouverez divers types de mobilier conçues sur mesure pour
                s&#39;intégrer parfaitement à votre espace de vie ou de travail.
                Vous pourrez également découvrir une gamme de produits
                d&#39;intérieure qui sont fabriqués avec soin et attention aux
                détails. Des produits de menuiserie de qualité supérieure pour
                améliorer l&#39;esthétique et la fonctionnalité de votre maison.
                Enfin, vous pourrez découvrir des conception architecturale pour
                aider à transformer votre espace en un endroit unique et sur
                mesure.
              </p>
            </div>
            <Image src={catalogueImgmobile} alt="catalogue" />
            <ul className="catalogue_table">
              <li>
                <Link href="/mobilier/">
                  <div className="catalogue_table_child">
                    <p>Mobilier</p>
                    <ArrowIcon />
                  </div>
                </Link>
              </li>
              <li>
                <Link href="/interieur/">
                  <div className="catalogue_table_child">
                    <p>Intérieur</p>
                    <ArrowIcon />
                  </div>
                </Link>
              </li>
              <li>
                <Link href="/produits/">
                  <div className="catalogue_table_child">
                    <p>Produits</p>
                    <ArrowIcon />
                  </div>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <div className="catalogue_table_child">
                    <p>Architecture</p>
                    <ArrowIcon />
                  </div>
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
};

export default Catalogue;
